
services:
  - type: web
    name: tiranga-smart-predictor
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python server/app.py"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://tirangaUser:<yourStrongPassword123>@cluster0.xep0rbi.mongodb.net/tiranga
